# Generated by Django 3.0.5 on 2020-04-29 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Text Content')),
                ('content_md5', models.UUIDField(editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_hash', models.TextField(verbose_name='original hash')),
                ('hash1', models.TextField(verbose_name='1st part of the hash')),
                ('hash2', models.TextField(verbose_name='2nd part of the hash')),
                ('hash3', models.TextField(verbose_name='3rd part of the hash')),
                ('hash4', models.TextField(verbose_name='4th part of the hash')),
            ],
            options={
                'index_together': {('hash1', 'hash3', 'hash4'), ('hash1', 'hash2', 'hash3'), ('hash2', 'hash3', 'hash4'), ('hash1', 'hash2', 'hash4')},
            },
        ),
    ]
